/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author A.I.S PERERA
 */
public class adminPharm extends javax.swing.JFrame {

    
    public adminPharm() {
        initComponents();
        setRecordsToTable();
    }

    DefaultTableModel tbm1;

    public void search(String str){

       tbm1 = (DefaultTableModel) table.getModel();
       TableRowSorter<DefaultTableModel>obj1 = new TableRowSorter<>(tbm1);
       table.setRowSorter(obj1);
       obj1.setRowFilter(RowFilter.regexFilter(str));

    }

    public void setRecordsToTable(){

        try{

        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject","root","");
        Statement stmt=con.createStatement();
        String sql="SElECT*FROM pharmacist";
        ResultSet rs=stmt.executeQuery(sql);


        while (rs.next()){

            String id=String.valueOf(rs.getInt("Ph_id"));
            String uName=rs.getString("User_name");
            String password=rs.getString("Password");
            String FName=rs.getString("Full_name");
            String pno=String.valueOf(rs.getInt("Phone_number"));
            String emaiil=rs.getString("Email");
            String nic=rs.getString("NIC");
            

            String tbData[]={id,uName,password,FName,pno,emaiil,nic};

            tbm1=(DefaultTableModel)table.getModel();

            tbm1.addRow(tbData);


       }


        }
        catch(Exception e2){
          System.out.println(e2);
      }

    }

    /*public void refresh(){

        DefaultTableModel tbm=(DefaultTableModel)table.getModel();
        tbm.setRowCount(0);
        tbm.fireTableDataChanged();

    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nametext = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        nametext1 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        nametext4 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        nametext6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        pw = new javax.swing.JTextField();
        Uname = new javax.swing.JTextField();
        nametext12 = new javax.swing.JLabel();
        nametext13 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        versionText3 = new javax.swing.JLabel();
        plusText3 = new javax.swing.JLabel();
        medlinkText3 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchtextfeild = new javax.swing.JTextField();
        medlinkText4 = new javax.swing.JLabel();
        nametext5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(850, 950));
        jPanel2.setMinimumSize(new java.awt.Dimension(850, 950));

        nametext.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        nametext.setForeground(new java.awt.Color(23, 107, 135));
        nametext.setText("Full Name");

        FName.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        nametext1.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        nametext1.setForeground(new java.awt.Color(23, 107, 135));
        nametext1.setText("NIC");

        nic.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        nametext4.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        nametext4.setForeground(new java.awt.Color(23, 107, 135));
        nametext4.setText("Phone NO");

        phoneNo.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        nametext6.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        nametext6.setForeground(new java.awt.Color(23, 107, 135));
        nametext6.setText("E-mail");

        email.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        pw.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        Uname.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N

        nametext12.setFont(new java.awt.Font("Lexend Deca", 1, 14)); // NOI18N
        nametext12.setForeground(new java.awt.Color(23, 107, 135));
        nametext12.setText("User Name");

        nametext13.setFont(new java.awt.Font("Lexend Deca", 1, 14)); // NOI18N
        nametext13.setForeground(new java.awt.Color(23, 107, 135));
        nametext13.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametext)
                    .addComponent(nametext4)
                    .addComponent(nametext12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(Uname, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(phoneNo))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametext13)
                    .addComponent(nametext6)
                    .addComponent(nametext1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pw, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(nic)
                    .addComponent(email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametext12)
                    .addComponent(nametext13))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nametext)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametext1)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nametext4)
                    .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametext6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel4.setkEndColor(new java.awt.Color(5, 59, 80));
        kGradientPanel4.setkStartColor(new java.awt.Color(23, 107, 135));

        versionText3.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        versionText3.setForeground(new java.awt.Color(100, 204, 197));
        versionText3.setText("v1.0");

        plusText3.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        plusText3.setForeground(new java.awt.Color(238, 238, 238));
        plusText3.setText("Plus");

        medlinkText3.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        medlinkText3.setForeground(new java.awt.Color(100, 204, 197));
        medlinkText3.setText("MediLink");

        backbutton.setBackground(new java.awt.Color(23, 107, 135));
        backbutton.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 14)); // NOI18N
        backbutton.setForeground(new java.awt.Color(238, 238, 238));
        backbutton.setText("BACK");
        backbutton.setBorder(null);
        backbutton.setContentAreaFilled(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medlinkText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plusText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionText3)
                .addGap(406, 406, 406))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(medlinkText3)
                .addComponent(plusText3)
                .addComponent(versionText3))
        );

        add.setBackground(new java.awt.Color(23, 107, 135));
        add.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        add.setForeground(new java.awt.Color(238, 238, 238));
        add.setText("ADD");
        add.setBorder(null);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(23, 107, 135));
        update.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        update.setForeground(new java.awt.Color(238, 238, 238));
        update.setText("UPDATE");
        update.setBorder(null);
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.setFocusPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(23, 107, 135));
        delete.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(238, 238, 238));
        delete.setText("DELETE");
        delete.setBorder(null);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Password", "Full Name", "Phone Number", "Email", "NIC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(30);
        table.setShowGrid(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        searchtextfeild.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N
        searchtextfeild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtextfeildKeyReleased(evt);
            }
        });

        medlinkText4.setFont(new java.awt.Font("Lexend Deca", 0, 18)); // NOI18N
        medlinkText4.setForeground(new java.awt.Color(23, 107, 135));
        medlinkText4.setText("Search here:");

        nametext5.setFont(new java.awt.Font("Lexend Deca Light", 0, 12)); // NOI18N
        nametext5.setForeground(new java.awt.Color(23, 107, 135));
        nametext5.setText("Clear");
        nametext5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nametext5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nametext5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nametext5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medlinkText4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchtextfeild, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 7, Short.MAX_VALUE))))
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(nametext5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(medlinkText4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchtextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new adminCon().setVisible(true);
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject","root","");
            Statement stmt=con.createStatement();
            stmt.execute("INSERT INTO pharmacist (User_name,Password,Full_name,Phone_number,Email,NIC) VALUES ('"+Uname.getText()+"','"+pw.getText()+"','"+FName.getText()+"','"+phoneNo.getText()+"','"+email.getText()+"','"+nic.getText()+"')");
            JOptionPane.showMessageDialog(this, "Data Inserted.");
            con.close();           

        }catch(Exception e){
            System.out.println(e);
        }

        tbm1.setRowCount(0);
        setRecordsToTable();

    }//GEN-LAST:event_addActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       //setRecordsToTable();

    }//GEN-LAST:event_formWindowOpened

    
 public int id;
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        id=Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString());
        Uname.setText(table.getValueAt(table.getSelectedRow(), 1).toString());
        pw.setText(table.getValueAt(table.getSelectedRow(), 2).toString());
        FName.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
        phoneNo.setText(table.getValueAt(table.getSelectedRow(), 4).toString());
        email.setText(table.getValueAt(table.getSelectedRow(), 5).toString());
        nic.setText(table.getValueAt(table.getSelectedRow(), 6).toString());


    }//GEN-LAST:event_tableMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject","root","");
        Statement stmt=con.createStatement();

        int n=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?");
        if(n==0){
            stmt.execute("DELETE FROM pharmacist WHERE Ph_id ="+id);
            formWindowOpened(null);
            //System.out.println("oop.Receptioncon.deleteActionPerformed()");
        }
        else{
            
        }

        }
        catch(Exception e4){
            System.out.println(e4);
        }

        tbm1.setRowCount(0);
        setRecordsToTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void searchtextfeildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtextfeildKeyReleased

        String s = searchtextfeild.getText();
        search(s);
        
    }//GEN-LAST:event_searchtextfeildKeyReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed




        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject","root","");
            Statement stmt=con.createStatement();
            stmt.execute("UPDATE pharmacist SET User_name='"+Uname.getText()+"',Password='"+pw.getText()+"',Full_name='"+FName.getText()+"',Phone_number='"+phoneNo.getText()+"',Email='"+email.getText()+"',NIC='"+nic.getText()+"'"
                    + "WHERE Ph_id ="+id);
            formWindowOpened(null);
            JOptionPane.showMessageDialog(this, "Data Updated.");
            con.close();

        }catch(Exception e){
            System.out.println(e);
        }

        tbm1.setRowCount(0);
        setRecordsToTable();


    }//GEN-LAST:event_updateActionPerformed

    private void nametext5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nametext5MouseClicked
        Uname.setText("");
        pw.setText("");
        FName.setText("");
        phoneNo.setText("");
        email.setText("");
        nic.setText("");      
    }//GEN-LAST:event_nametext5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPharm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FName;
    private javax.swing.JTextField Uname;
    private javax.swing.JButton add;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel medlinkText3;
    private javax.swing.JLabel medlinkText4;
    private javax.swing.JLabel nametext;
    private javax.swing.JLabel nametext1;
    private javax.swing.JLabel nametext12;
    private javax.swing.JLabel nametext13;
    private javax.swing.JLabel nametext4;
    private javax.swing.JLabel nametext5;
    private javax.swing.JLabel nametext6;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JLabel plusText3;
    private javax.swing.JTextField pw;
    private javax.swing.JTextField searchtextfeild;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    private javax.swing.JLabel versionText3;
    // End of variables declaration//GEN-END:variables
}
