/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author A.I.S PERERA
 */
public class receplogin extends javax.swing.JFrame {

    /**
     * Creates new form Adminlogin
     */
    public receplogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        versionText = new javax.swing.JLabel();
        plusText = new javax.swing.JLabel();
        medlinkText = new javax.swing.JLabel();
        loginlext = new javax.swing.JLabel();
        usernametext = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordtext = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        backtowelcomescreen = new javax.swing.JLabel();
        forgetPw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(5, 59, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(23, 107, 135));

        versionText.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        versionText.setForeground(new java.awt.Color(100, 204, 197));
        versionText.setText("v1.0");

        plusText.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 36)); // NOI18N
        plusText.setForeground(new java.awt.Color(238, 238, 238));
        plusText.setText("Plus");

        medlinkText.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 36)); // NOI18N
        medlinkText.setForeground(new java.awt.Color(100, 204, 197));
        medlinkText.setText("MediLink");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(medlinkText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plusText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionText)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medlinkText)
                    .addComponent(plusText)
                    .addComponent(versionText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginlext.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        loginlext.setForeground(new java.awt.Color(23, 107, 135));
        loginlext.setText("LOGIN AS RECEPTION");

        usernametext.setFont(new java.awt.Font("Lexend Deca Light", 1, 14)); // NOI18N
        usernametext.setForeground(new java.awt.Color(23, 107, 135));
        usernametext.setText("User Name");

        passwordtext.setFont(new java.awt.Font("Lexend Deca Light", 1, 14)); // NOI18N
        passwordtext.setForeground(new java.awt.Color(23, 107, 135));
        passwordtext.setText("Password");

        loginbutton.setBackground(new java.awt.Color(23, 107, 135));
        loginbutton.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 18)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(238, 238, 238));
        loginbutton.setText("LOGIN");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        backtowelcomescreen.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        backtowelcomescreen.setForeground(new java.awt.Color(23, 107, 135));
        backtowelcomescreen.setText("Back to Welcome screen");
        backtowelcomescreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtowelcomescreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtowelcomescreenMouseClicked(evt);
            }
        });

        forgetPw.setFont(new java.awt.Font("Lexend Deca Light", 0, 12)); // NOI18N
        forgetPw.setForeground(new java.awt.Color(23, 107, 135));
        forgetPw.setText("Forget password");
        forgetPw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPwMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(backtowelcomescreen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(loginlext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgetPw)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernametext)
                                .addComponent(username)
                                .addComponent(passwordtext)
                                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(loginlext, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernametext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgetPw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backtowelcomescreen)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtowelcomescreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtowelcomescreenMouseClicked
        new WelcomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_backtowelcomescreenMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        try{
         Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/oopproject","root","");
            Statement stmt=con.createStatement();
            String sql="SELECT*FROM receptionist WHERE User_name='"+username.getText()+"' AND Password='"+password.getText()+"'";
            ResultSet rs=stmt.executeQuery(sql);

            if(rs.next()){
            new Receptioncon().setVisible(true);
            dispose();
            }
            else{
            JOptionPane.showMessageDialog(null,"User name and Password doesn't match!");
            }
            con.close();
        }
        catch(Exception e1){
            System.out.println(e1);
        }

    }//GEN-LAST:event_loginbuttonActionPerformed

    private void forgetPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPwMouseClicked

        JOptionPane.showMessageDialog(null, "Contact Admin Using 0773064927 or Indduru@gmail.com");
    }//GEN-LAST:event_forgetPwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receplogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backtowelcomescreen;
    private javax.swing.JLabel forgetPw;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginlext;
    private javax.swing.JLabel medlinkText;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JLabel plusText;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernametext;
    private javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
}
