/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop;

/**
 *
 * @author A.I.S PERERA
 */
public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        medlinkText = new javax.swing.JLabel();
        plusText = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        versionText = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        receptionbutton = new javax.swing.JButton();
        doctorbutton = new javax.swing.JButton();
        pharmacistbutton = new javax.swing.JButton();
        setectText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setMaximumSize(new java.awt.Dimension(793, 440));
        setMinimumSize(new java.awt.Dimension(793, 440));
        setPreferredSize(new java.awt.Dimension(793, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(5, 59, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(23, 107, 135));

        medlinkText.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        medlinkText.setForeground(new java.awt.Color(100, 204, 197));
        medlinkText.setText("MediLink");

        plusText.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 24)); // NOI18N
        plusText.setForeground(new java.awt.Color(238, 238, 238));
        plusText.setText("Plus");

        welcomeText.setFont(new java.awt.Font("Lexend Deca ExtraBold", 0, 48)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(100, 204, 197));
        welcomeText.setText("Hello! Welcome back");

        versionText.setFont(new java.awt.Font("Lexend Deca Light", 0, 14)); // NOI18N
        versionText.setForeground(new java.awt.Color(100, 204, 197));
        versionText.setText("v1.0");

        adminButton.setBackground(new java.awt.Color(5, 59, 80));
        adminButton.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        adminButton.setForeground(new java.awt.Color(238, 238, 238));
        adminButton.setText("ADMIN");
        adminButton.setToolTipText("login as admin");
        adminButton.setBorderPainted(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setFocusPainted(false);
        adminButton.setFocusable(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        receptionbutton.setBackground(new java.awt.Color(5, 59, 80));
        receptionbutton.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        receptionbutton.setForeground(new java.awt.Color(238, 238, 238));
        receptionbutton.setText("RECEPTION");
        receptionbutton.setToolTipText("login as receptionist");
        receptionbutton.setBorderPainted(false);
        receptionbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        receptionbutton.setFocusPainted(false);
        receptionbutton.setFocusable(false);
        receptionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionbuttonActionPerformed(evt);
            }
        });

        doctorbutton.setBackground(new java.awt.Color(5, 59, 80));
        doctorbutton.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        doctorbutton.setForeground(new java.awt.Color(238, 238, 238));
        doctorbutton.setText("DOCTOR");
        doctorbutton.setToolTipText("login as doctor");
        doctorbutton.setBorderPainted(false);
        doctorbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorbutton.setFocusPainted(false);
        doctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbuttonActionPerformed(evt);
            }
        });

        pharmacistbutton.setBackground(new java.awt.Color(5, 59, 80));
        pharmacistbutton.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        pharmacistbutton.setForeground(new java.awt.Color(238, 238, 238));
        pharmacistbutton.setText("PHARMACIST");
        pharmacistbutton.setToolTipText("login as pharmacist ");
        pharmacistbutton.setBorderPainted(false);
        pharmacistbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharmacistbutton.setFocusPainted(false);
        pharmacistbutton.setFocusable(false);
        pharmacistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistbuttonActionPerformed(evt);
            }
        });

        setectText.setFont(new java.awt.Font("Lexend Deca SemiBold", 0, 18)); // NOI18N
        setectText.setForeground(new java.awt.Color(100, 204, 197));
        setectText.setText("----- Select a role to Login -----");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(medlinkText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionText)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeText)
                        .addGap(127, 127, 127))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setectText)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(receptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pharmacistbutton)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medlinkText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionText))
                .addGap(18, 18, 18)
                .addComponent(welcomeText)
                .addGap(43, 43, 43)
                .addComponent(setectText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receptionbutton)
                    .addComponent(doctorbutton)
                    .addComponent(pharmacistbutton))
                .addGap(512, 512, 512))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        new Adminlogins().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void receptionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionbuttonActionPerformed
        new receplogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_receptionbuttonActionPerformed

    private void doctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbuttonActionPerformed
        new Doclogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_doctorbuttonActionPerformed

    private void pharmacistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistbuttonActionPerformed
        new Phamlogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_pharmacistbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton doctorbutton;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel medlinkText;
    private javax.swing.JButton pharmacistbutton;
    private javax.swing.JLabel plusText;
    private javax.swing.JButton receptionbutton;
    private javax.swing.JLabel setectText;
    private javax.swing.JLabel versionText;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
